### ISSUE TITLE
Documentation tool doesn't scale the iframe right in Moodle

### ISSUE THREAD

**Issue by Jarvil** [h5p/h5p-documentation-tool#3]
Hello

documentation tool seems to scale its displayed page length according how long the first page is. This is clearly a bug, since if you have short first page and long second page you cannot see navigation buttons at all at the bottoms of the page.

This bug seesm to appear somewhere between versions  Documentation Tool (1.4.0) -> Documentation Tool (1.5.2) since in version 1.4.0 the bug doesn't exist. Tested with Moodle 3.3 & mod_hvp 1.5 &  Documentation Tool (1.5.2).

Steps to recreate:

1. Create H5P-activity in Moodle
2. Select documentation tool
3. Add a standard page as first page select  
- library type "text" 
- type first page to title and text-fields.

4. Add second Second page and 

- as library type select "text input field editor element"
- give it description "question 1" 
- select "input field size" 10 lines.

5. Repeat this two more times so you have 3 questions on this page.

6. save and display
6. Notice that on the second page you can see only first two questions, question 3 isn't seen and neither is no navigation buttons.
 
If you open this tab to separate browser window and resize it the question 3 comes in the view but not before this.

<hr>

Creating the H5P-activity;
![doc1](https://user-images.githubusercontent.com/15193418/30848293-69e53cb4-a2a7-11e7-8120-76360f07e84e.PNG)

![doc2](https://user-images.githubusercontent.com/15193418/30848296-6d34ab70-a2a7-11e7-9953-2c8036951a83.PNG)

![doc3](https://user-images.githubusercontent.com/15193418/30848306-713ba9d0-a2a7-11e7-9fa4-d7cbf11d0067.PNG)

![doc4](https://user-images.githubusercontent.com/15193418/30848315-7452a790-a2a7-11e7-9f8d-0fdad293253e.PNG)

![doc5](https://user-images.githubusercontent.com/15193418/30848320-77a0f1f4-a2a7-11e7-9c5c-46a5be600226.png)

# **Below you can see that question "tell me 3" isn't displayed at all on the second long page and neither is navigation buttons**

![doc6](https://user-images.githubusercontent.com/15193418/30848327-7aaa508e-a2a7-11e7-9d63-1d46b8c561f9.png)

# **Only after resizing the window "tell me 3" and navigation buttons are displayed**

![doc7](https://user-images.githubusercontent.com/15193418/30848332-7db07fec-a2a7-11e7-8cb0-6b97f6f36f27.PNG)

![doc8](https://user-images.githubusercontent.com/15193418/30848336-806f57a8-a2a7-11e7-8738-16e348993566.PNG)

**Comment by Jarvil** [comment]
![doc8](https://user-images.githubusercontent.com/15193418/30848267-56957c82-a2a7-11e7-97e8-c2c9e2b47f06.PNG)
![doc7](https://user-images.githubusercontent.com/15193418/30848268-56959050-a2a7-11e7-8a15-a45f26ac463d.PNG)
![doc6](https://user-images.githubusercontent.com/15193418/30848270-5697929c-a2a7-11e7-8e4c-632bbbf4ac17.png)
![doc5](https://user-images.githubusercontent.com/15193418/30848269-56973982-a2a7-11e7-958d-142fd2644d07.png)
![doc4](https://user-images.githubusercontent.com/15193418/30848272-569cb6f0-a2a7-11e7-8b1f-c490a51af08f.PNG)
![doc3](https://user-images.githubusercontent.com/15193418/30848271-5697a160-a2a7-11e7-9459-78f0d98b50a2.PNG)
![doc2](https://user-images.githubusercontent.com/15193418/30848274-56c8a530-a2a7-11e7-8bc6-95395fc8f405.PNG)
![doc1](https://user-images.githubusercontent.com/15193418/30848273-56b600f6-a2a7-11e7-8d6b-b422384d1744.PNG)

**Comment by Jarvil** [comment]
Is there anyway to downgrade documentation tool library back to version 1.4.0 ?

**Comment by Jarvil** [comment]
Any progress on fixing this? This block updating the documentation tool from version 1.4.0 @falcon-git

**Comment by timothyylim** [comment]
Hi @Jarvil, I'm sorry this was not handled earlier. Unfortunately, there is no way to downgrade the library version. You will have to restore to a backed up version of your content if you have it. I can understand this is quite frustrating and it should really have been caught in testing before deployment. 

I've created an issue for it here:

 https://h5ptechnology.atlassian.net/browse/HFP-1601

**Comment by fnoks** [comment]
This should already be solved. Please upgrade to latest version of documentation tool, and let us know if that solves the issue for you.

**Comment by Jarvil** [comment]
Hello,

This seems to be fixed in documentation tool 1.5.3, thank you.
