### ISSUE TITLE
Export text also prints out html tags

### ISSUE THREAD

**Issue by Jarvil** [h5p/h5p-documentation-tool#4]
Hello,

If you have document export page the docx file output with "export text"  will dipslay all the html-tags that you have used to stylize your text on a standard pages "Description of inputfield"-field are displayed in the docx-file f.ex <strong>Tell me</strong>

![question1](https://user-images.githubusercontent.com/15193418/30849246-64b8a034-a2aa-11e7-90c3-37a0594ba728.PNG)

![question2](https://user-images.githubusercontent.com/15193418/30849256-6825df5c-a2aa-11e7-9728-c97999362446.PNG)

**Comment by Jarvil** [comment]
Have you already looked at this @fnoks

**Comment by fnoks** [comment]
This is a known bug. There are two different solutions:
1) Strip away HTML tags when generating the document
2) Convert the tags to the markup (xml?) understood by the doc file

If someone is willing to create a pull request for this, I will be more then happy to review it and merge it in!

**Comment by Jarvil** [comment]
Hello,

Any progress on this fix? @fnoks

**Comment by fnoks** [comment]
@Jarvil : No progress afaik, unfortunately.

**Comment by Jarvil** [comment]
Hello,

any progress on this @fnoks

**Comment by fnoks** [comment]
It is fixed here: https://github.com/h5p/h5p-text-input-field/commit/d173ba06e8c1cab85488e80f4f0b2d46af9f2f6d

I.e: it removes any HTML tags when generating the document. It will be part of the next release of doc-tool (ETA not set)
